- sample/src/main/java/com/walletconnect/sample/SampleApplication.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/util/UtilFunctions.kt
- walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/PairingDao.sq
- walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/SessionDao.sq
Check expiry when a sequence is fetched from DB. When expired delete all data coupled with sequence.
> Check expiry when fetching sequence from DB

- dapp/src/main/kotlin/com/walletconnect/dapp/DappSampleApplication.kt
- sample/src/main/java/com/walletconnect/sample/SampleApplication.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnect.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/adapters/RelayDOJsonRpcResultJsonAdapter.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/common/SessionParticipantVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/session/params/SessionParamsVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/jsonRpc/JsonRpcResponseVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/sequence/PairingVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/model/mapper/EngineMapper.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/data/serializer/JsonRpcSerializer.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/domain/WalletConnectRelayer.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/model/RelayDO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/model/mapper/RelayMapper.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
- walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/PairingDao.sq
- walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/SessionDao.sq
- walletconnectv2/src/test/kotlin/com/walletconnect/walletconnectv2/core/adapters/RelayDOJsonRpcResponseJsonRpcResultJsonAdapterTest.kt
- Sync with swift wallet and dapp
- Fix peer pairing metadata
> Swift sync

- sample/src/main/java/com/walletconnect/sample/wallet/WalletViewModel.kt
- walletconnectv2/src/androidTest/kotlin/com/walletconnect/walletconnectv2/wallet/WalletClientIntegrationAndroidTest.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnect.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/mapper/ClientMapper.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/exceptions/client/ClientExceptions.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/exceptions/client/ClientMessages.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/exceptions/peer/PeerError.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/utils/JsonRpcMethod.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/common/SessionPermissionsVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/pairing/params/PairingParamsVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/session/SessionSettlementVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/session/params/SessionParamsVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/session/payload/EventVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/session/payload/EventsVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/clientsync/session/payload/SessionEventVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/sequence/SessionVO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/di/StorageModule.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/Validator.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/model/EngineDO.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/model/mapper/EngineMapper.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/data/serializer/JsonRpcSerializer.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
- walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/SessionDao.sq
- walletconnectv2/src/test/kotlin/com/walletconnect/walletconnectv2/ValidatorTest.kt
- walletconnectv2/src/test/kotlin/com/walletconnect/walletconnectv2/crypto/codec/ChaChaPolyCodecTest.kt
Add new internal update calls.
Add new peer responses for new update methods.
Refactor validation.
Add new storage methods for updates.
> Internal calls refactor for update methods

- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/AuthClient.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/data/serializer/JsonRpcSerializer.kt
- walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/domain/RelayerInteractor.kt
- walletconnectv2/src/test/kotlin/com/walletconnect/walletconnectv2/relay/domain/RelayerInteractorTest.kt
Just minor naming improvements
> Naming clean up

- buildSrc/src/main/kotlin/Dependencies.kt
Related to: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/286
> Upgrade Koin to 3.2.0

- .github/workflows/intake.yml
As requested
Also fixes a bug where only users that are "publicly" members of WalletConnect are recognized as team members.
> fix: only adds issues not PRs

- auth/requester/src/main/kotlin/com/walletconnect/requester/ui/connect/ConnectFragment.kt
- auth/requester/src/main/kotlin/com/walletconnect/requester/ui/connect/ConnectViewModel.kt
- auth/requester/src/main/kotlin/com/walletconnect/requester/ui/events/RequesterEvents.kt
If you clicked "Sign in with WalletConnect" button before establishing connecction with the relay server you get stuck on waiting animation
> fix: Add connection check before connecting

- chat/sdk/src/main/kotlin/com/walletconnect/chat/client/mapper/ClientMapper.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/di/StorageModule.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/ContactStorageRepository.kt
Merge after #633 
Next in line #638
> refactor: Contacts cleanup

- androidCore/sdk/src/test/kotlin/com/walletconnect/android/internal/common/ClientIdJwtRepositoryAndroidTest.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/jwt/DidJwtRepository.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/ContactStorageRepository.kt
- foundation/src/main/kotlin/com/walletconnect/foundation/crypto/data/repository/BaseClientIdJwtRepository.kt
- foundation/src/main/kotlin/com/walletconnect/foundation/util/jwt/JwtUtils.kt
- foundation/src/test/kotlin/com/walletconnect/foundation/crypto/data/repository/JwtRepositoryTest.kt
Merge after #635 
Next in line #639
> refactor: Jwt Utils

- chat/sdk/src/main/kotlin/com/walletconnect/chat/common/model/Account.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/di/EngineModule.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/di/StorageModule.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/AccountsStorageRepository.kt
- chat/sdk/src/main/sqldelight/com/walletconnect/chat/storage/data/dao/Accounts.sq
Merge after #639
Next in line #642
> feat: Add account storage

- chat/sample/src/main/kotlin/com/walletconnect/chatsample/ui/shared/ChatSharedEvents.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/client/mapper/ClientMapper.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/common/exceptions/ChatExceptions.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/common/model/Invite.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/common/model/JsonRpcHistoryEntry.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/di/EngineModule.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/json_rpc/GetPendingJsonRpcHistoryEntryByIdUseCase.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/InvitesStorageRepository.kt
- chat/sdk/src/main/sqldelight/com/walletconnect/chat/storage/data/dao/Invites.sq
Merge after #641 
Next in line #646
> feat: Add Invite requests

- chat/sample/src/main/kotlin/com/walletconnect/chatsample/ui/shared/ChatSharedViewModel.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/client/ChatProtocol.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/client/mapper/ClientMapper.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/common/model/Invite.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/common/model/Thread.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/di/EngineModule.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/di/StorageModule.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/AccountsStorageRepository.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/IdentitiesStorageRepository.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/InvitesStorageRepository.kt
- chat/sdk/src/main/kotlin/com/walletconnect/chat/storage/ThreadsStorageRepository.kt
- chat/sdk/src/main/sqldelight/com/walletconnect/chat/storage/data/dao/Accounts.sq
- chat/sdk/src/main/sqldelight/com/walletconnect/chat/storage/data/dao/Identities.sq
- chat/sdk/src/main/sqldelight/com/walletconnect/chat/storage/data/dao/Invites.sq
- chat/sdk/src/main/sqldelight/com/walletconnect/chat/storage/data/dao/Threads.sq
> feat: Persistent listening and Identities

- androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/utils/CoreValidator.kt
- androidCore/sdk/src/test/kotlin/com/walletconnect/android/internal/CoreValidatorTest.kt
Resolves: #732 
Casa specs: https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md#syntax
> fix: Comply with CAIP10 regex

- samples/wallet/src/main/kotlin/com/walletconnect/sample/wallet/Web3WalletApplication.kt
- web3/wallet/src/main/kotlin/com/walletconnect/web3/wallet/client/Web3Wallet.kt
Docs: https://github.com/WalletConnect/walletconnect-docs/pull/586
> feat: add register device token to web3wallet

- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/Sync.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/SyncInterface.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/SyncProtocol.kt
> feat: Add Sync API interface

- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/Sync.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/SyncInterface.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/SyncProtocol.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/mapper/ClientMapper.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/common/model/Events.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/common/model/Store.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/common/model/SyncUpdate.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/crypto/MessageSigner.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/di/EngineModule.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/domain/SyncEngine.kt
> feat: Add Sync Protocol

- androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/DBUtils.kt
- sync/sdk/build.gradle.kts
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/SyncProtocol.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/mapper/ClientMapper.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/common/model/Account.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/common/model/Entropy.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/di/EngineModule.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/di/StorageModule.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/RegisterUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/SuspendUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/storage/AccountsStorageRepository.kt
- sync/sdk/src/main/sqldelight/com/walletconnect/sync/data/dao/Accounts.sq
> feat: Add sync registration with storage

- sync/sdk/src/main/kotlin/com/walletconnect/sync/di/EngineModule.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/domain/SyncEngine.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/calls/CreateStoreUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/calls/DeleteStoreValueUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/calls/RegisterAccountUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/calls/SetStoreValueUseCase.kt
> refactor: Rename usecases to be more descriptive

- samples/wallet/build.gradle.kts
- samples/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/common/WCTopAppBar.kt
- samples/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/connections/ConnectionsRoute.kt
- samples/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/notifications/NotificiationsScreenRoute.kt
> feat: Add current bom version

- sync/sdk/src/main/kotlin/com/walletconnect/sync/di/EngineModule.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/domain/SyncEngine.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/calls/DeleteStoreValueUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/calls/SetStoreValueUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/requests/incoming/OnDeleteRequestUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/requests/incoming/OnSetRequestUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/engine/use_case/requests/outgoing/SendSetRequestUseCase.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/storage/StoresStorageRepository.kt
- sync/sdk/src/main/sqldelight/com/walletconnect/sync/data/dao/Stores.sq
> feat: Send wc_syncSet request after local storage update

- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/Sync.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/SyncProtocol.kt
- sync/sdk/src/main/kotlin/com/walletconnect/sync/client/mapper/ClientMapper.kt
> feat: Wrap internal AccountId for Sync

- ReadMe.md
- androidCore/sdk/src/debug/kotlin/com/walletconnect/android/di/CoreStorageModule.kt
- androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
- androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/BaseStorageModule.kt
- androidCore/sdk/src/main/kotlin/com/walletconnect/android/sync/di/SyncStorageModule.kt
- buildSrc/src/main/kotlin/Versions.kt
> fix: SyncEngine initialization

- sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/proposal/ProposalVO.kt
Should we merge this PR into master instead?
> fix: Fix redirect on session request approve

- androidCore/sdk/src/main/kotlin/com/walletconnect/android/sync/engine/use_case/calls/GetMessageUseCase.kt
- androidCore/sdk/src/test/kotlin/com/walletconnect/android/sync/PrototypeTest.kt
> feat: Update sync message

- androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/utils/CoreValidator.kt
- androidCore/sdk/src/test/kotlin/com/walletconnect/android/internal/CoreValidatorTest.kt
https://github.com/ChainAgnostic/CAIPs/commit/cbee09d2885065ba15482398828d5c5e3ac57faa
> fix: Fix incorrect CAIP2 reference regex

- core/android/src/main/kotlin/com/walletconnect/android/internal/common/di/ExplorerModule.kt
- core/android/src/main/kotlin/com/walletconnect/android/internal/common/explorer/ExplorerRepository.kt
- core/android/src/main/kotlin/com/walletconnect/android/internal/common/explorer/data/model/Wallet.kt
- core/android/src/main/kotlin/com/walletconnect/android/utils/PackageManagerExtensions.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/components/Wallets.kt
- sample/dapp/src/main/AndroidManifest.xml
- sample/dapp/src/main/kotlin/com/walletconnect/sample/dapp/ui/routes/composable_routes/chain_selection/ChainSelectionRoute.kt
> Show installed wallets

- core/android/src/main/kotlin/com/walletconnect/android/internal/common/explorer/data/model/Wallet.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/client/WalletConnectModal.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/di/WalletConnectModalModule.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/domain/RecentWalletsRepository.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/domain/WalletConnectModalStorage.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/domain/usecase/GetRecentWalletUseCase.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/domain/usecase/SaveRecentWalletUseCase.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/WalletConnectModal.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/WalletConnectModalViewModel.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/components/Wallets.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/navigation/ModalNavGraph.kt
- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/routes/connect_wallet/ConnectYourWalletRoute.kt
- product/walletconnectmodal/src/test/kotlin/com/walletconnect/wcmodal/ui/WalletConnectModalViewModelTest.kt
Based on two PRs:
#1039 
#1047 
Resolves: #1029
> [WCM] Recents wallets 

- core/android/src/androidTest/kotlin/com/walletconnect/android/test/client/HistoryInstrumentedAndroidTest.kt
- core/android/src/main/kotlin/com/walletconnect/android/history/HistoryInterface.kt
- core/android/src/main/kotlin/com/walletconnect/android/history/HistoryProtocol.kt
- core/android/src/main/kotlin/com/walletconnect/android/history/network/model/messages/MessagesParams.kt
- core/android/src/main/kotlin/com/walletconnect/android/history/network/model/messages/MessagesResponse.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/sync/use_case/GetMessagesFromHistoryUseCase.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/sync/use_case/events/OnSubscriptionUpdateEventUseCase.kt
- protocol/push/src/main/kotlin/com/walletconnect/push/engine/sync/use_case/GetMessagesFromHistoryUseCase.kt
- protocol/push/src/main/kotlin/com/walletconnect/push/engine/sync/use_case/events/OnSubscriptionUpdateEventUseCase.kt
Do not merge before: https://github.com/WalletConnect/WalletConnectKotlinV2/pull/1073
> [History] Fetch all messages instead of one batch

- product/walletconnectmodal/src/main/kotlin/com/walletconnect/wcmodal/ui/WalletConnectModalViewModel.kt
- product/walletconnectmodal/src/test/kotlin/com/walletconnect/wcmodal/ui/WalletConnectModalViewModelTest.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalViewModel.kt
Also replace Timber with Logger
> [WCM][W3M] Fix for launching coroutine twice

- protocol/notify/src/main/kotlin/com/walletconnect/notify/common/NotifyServerUrl.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/di/NotifyEngineModule.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/di/RequestModule.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/domain/WatchSubscriptionsUseCase.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/requests/OnNotifyDeleteUseCase.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/requests/OnNotifyMessageUseCase.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/requests/OnSubscriptionsChangedUseCase.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifyUpdateResponseUseCase.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnWatchSubscriptionsResponseUseCase.kt
Went through code one last time, and found some missing pieces
- Extract Notify Server Url from usecases
- Add validation plan. I don't want to force it now becaues it requires adding new table for storing keys from did.json files
> [Notify] Polish before hackaton

- core/android/src/main/kotlin/com/walletconnect/android/internal/common/explorer/ExplorerRepository.kt
- core/android/src/main/kotlin/com/walletconnect/android/internal/common/modal/Web3ModalApiRepository.kt
- core/android/src/main/kotlin/com/walletconnect/android/utils/PackageManagerExtensions.kt
- core/modal/src/main/kotlin/com/walletconnect/modal/utils/UriExtensions.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/connect_wallet/ConnectWalletRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/redirect/RedirectState.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/redirect/RedirectWalletScreen.kt
- Add NotDetected state on redirect screen
- Fix is wallet installed
- Format total wallets size
> [W3M] Redirect screen improvements

- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/client/Web3Modal.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3Modal.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalSheet.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalState.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalViewModel.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/ComponentDelegate.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/button/ConnectButton.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/button/Web3ModalState.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/Web3ModalComponent.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/utils/Lifecycle.kt
- product/web3modal/src/main/res/navigation/web3modal_graph.xml
- sample/modal/src/main/res/navigation/nav_graph.xml
- Expose Web3ModalComponent for developers
- Add component delegate
> [W3M] Expose modal Web3ModalComponent and ComponentDelegate

- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalSheet.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalTheme.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/Web3ModalStates.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/Web3ModalTopBar.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Dividers.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Help.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Icons.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Loading.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/account/AccountName.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/button/ButtonStyle.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/button/LinkButton.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/entry/AccountEntry.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/entry/ActionEntry.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/entry/StoreEntry.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/inputs/SearchInput.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/switch/PlatformTabRow.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/account/AccountRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/choose_network/ChooseNetworkRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/redirect/RedirectWalletScreen.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/scan_code/ScanCodeRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/theme/Typography.kt
- sample/modal/src/main/kotlin/com/walletconnect/sample/modal/MainActivity.kt
- sample/modal/src/main/kotlin/com/walletconnect/sample/modal/ModalSampleApp.kt
- sample/modal/src/main/kotlin/com/walletconnect/sample/modal/ui/LabScreen.kt
- sample/modal/src/main/kotlin/com/walletconnect/sample/modal/ui/PredifinedThemes.kt
- Adjust typography names to match figma
- Add link button
- Change copy button to link button
- Change PlayStore button to  new design
> [W3M] Design system mode typography adjustments

- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalSheet.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/Web3ModalTheme.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/button/AccountButton.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Dividers.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Help.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Icons.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Label.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/ListSelect.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Loading.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/Wallets.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/account/AccountImage.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/button/ButtonStyle.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/entry/BaseEntry.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/entry/StoreEntry.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/inputs/InputCancel.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/inputs/SearchInput.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/network/ChainNetworkIcons.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/network/ChainNetworkItem.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/commons/switch/PlatformTabRow.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/snackbar/ModalSnackBar.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/components/internal/walletconnect/WalletConnectLogo.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/common/WhatIsNetwork.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/all_wallets/AllWalletsRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/redirect/RedirectWalletScreen.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/scan_code/ScanCodeRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/theme/Web3ModalColors.kt
- product/web3modal/src/main/res/values/attrs.xml
- sample/modal/src/main/kotlin/com/walletconnect/sample/modal/ui/PredifinedThemes.kt
Renaming colors and remove unused methods
> [W3M] Renaming colors name to match figma

- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/model/UiState.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/AccountNavigationGraph.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/ConnectNavigationGraph.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/ConnectState.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/utils/Navigation.kt
Adjust navigation animation to web version
https://github.com/WalletConnect/WalletConnectKotlinV2/assets/18551562/011928e2-a616-48fe-b7e7-f67b83c952bd
> [W3M] Change navigation to slideIn and slideOut also adapting ui builder to slide anim

- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/domain/NotificationHandler.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/notifications/NotificiationsScreenRoute.kt
Merge after https://github.com/WalletConnect/WalletConnectKotlinV2/pull/1217
> [W3W Sample] Add url redirection on PN

- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/domain/RegisterIdentityUseCase.kt
As per specs: https://github.com/WalletConnect/walletconnect-specs/pull/174.
> [Notify] Update statement

- core/android/src/debug/kotlin/com/walletconnect/android/di/CoreStorageModule.kt
- core/android/src/main/kotlin/com/walletconnect/android/internal/common/di/BaseStorageModule.kt
- core/android/src/release/kotlin/com.walletconnect.android/di/CoreStorageModule.kt
- protocol/chat/src/main/kotlin/com/walletconnect/chat/di/StorageModule.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/data/storage/MessagesRepository.kt
- protocol/notify/src/main/kotlin/com/walletconnect/notify/di/NotifyStorageModule.kt
- protocol/sign/src/main/kotlin/com/walletconnect/sign/di/StorageModule.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/Web3WalletApplication.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/domain/NotificationHandler.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/Web3WalletActivity.kt
Fixes wrong koin declaration and improves notification displaying within sample app
> fix: Schema koin declaration

- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/navigation/Navigator.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/navigation/account/Navigation.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/navigation/connection/RedirectNavigation.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/AccountNavigationGraph.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/AccountViewModel.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/account/AccountRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/chain_redirect/ChainSwitchRedirect.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/account/change_network/ChangeNetworkRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/ConnectNavigationGraph.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/ConnectViewModel.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/all_wallets/AllWalletsRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/choose_network/ChooseNetworkRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/connect_wallet/ConnectWalletRoute.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/redirect/RedirectWalletScreen.kt
- product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/ui/routes/connect/scan_code/ScanCodeRoute.kt
To optimize the modal, I changed Compose state to ViewModels, now the data persists a configuration changes
> [W3M] Migrate to viewModels from states

- protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/domain/RegisterIdentityUseCase.kt
Update to conform to latest specs
> [Notify] chore: Update SIWE statement

- .github/workflows/ci_instrumented_tests.yml
Will fix&enable them before release. Now they seem to cause issue.
> [Notify] chore: Disable flaky tests

- core/android/src/main/kotlin/com/walletconnect/android/pairing/client/PairingProtocol.kt
- core/android/src/main/kotlin/com/walletconnect/android/relay/NetworkClientTimeout.kt
Increase OkHttp and pairing timeouts after testing on 2G (EDGE, GSM) to improve the flow
> feat: increase timeouts

- core/android/src/androidTest/kotlin/com/walletconnect/android/test/client/KeyserverInstrumentedAndroidTest.kt
- core/android/src/androidTest/kotlin/com/walletconnect/android/test/utils/TestClient.kt
- core/android/src/main/kotlin/com/walletconnect/android/CoreProtocol.kt
- core/android/src/main/kotlin/com/walletconnect/android/relay/RelayClient.kt
- protocol/notify/src/androidTest/kotlin/com/walletconnect/notify/di/OverrideModule.kt
- protocol/notify/src/androidTest/kotlin/com/walletconnect/notify/test/utils/TestClient.kt
- protocol/sign/src/androidTest/kotlin/com/walletconnect/sign/di/OverrideModule.kt
- protocol/sign/src/androidTest/kotlin/com/walletconnect/sign/test/utils/TestClient.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/Web3WalletApplication.kt
- clean up Relay initialization
- move networking module and wss initialization to the top of the order of initialization
> core: clean up Relay initialization

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/editor.xml
added coding style to git to make styling consistent
> [meta] add coding style

- .gitignore
- core/android/src/main/kotlin/com/walletconnect/android/internal/common/json_rpc/domain/relay/RelayJsonRpcInteractor.kt
- protocol/sign/src/androidTest/kotlin/com/walletconnect/sign/test/client/SignClientInstrumentedAndroidTest.kt
- protocol/sign/src/androidTest/kotlin/com/walletconnect/sign/test/utils/wallet/WalletSignClient.kt
- protocol/sign/src/main/kotlin/com/walletconnect/sign/common/adapters/SessionEventVOJsonAdapter.kt
- protocol/sign/src/main/kotlin/com/walletconnect/sign/common/adapters/SessionRequestVOJsonAdapter.kt
- protocol/sign/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/session/payload/SessionEventVO.kt
- protocol/sign/src/main/kotlin/com/walletconnect/sign/di/SignJsonRpcModule.kt
- protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/EmitEventUseCase.kt
- protocol/sign/src/test/kotlin/com/walletconnect/sign/adapters/SessionEventVOJsonAdapterTest.kt
- protocol/sign/src/test/kotlin/com/walletconnect/sign/adapters/SessionRequestVOJsonAdapterTest.kt
- protocol/sign/src/test/kotlin/com/walletconnect/sign/engine/use_case/calls/EmitEventUseCaseTest.kt
- protocol/sign/src/test/kotlin/com/walletconnect/sign/util/UtilFunctions.kt
- sample/wallet/build.gradle.kts
- sample/wallet/src/main/AndroidManifest.xml
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/domain/TestAccounts.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/common/peer/PeerSection.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/connection_details/ConnectionDetailsRoute.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/connections/ConnectionsRoute.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/connections/ConnectionsViewModel.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalUI.kt
- sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalViewModel.kt
Added:
- Switch Account feature to Kotlin Sample Wallet
- Custom JSON adapter for parsing session event
> feat: account switch in sample wallet
